### ISSUE TITLE
(node:10604) UnhandledPromiseRejectionWarning: Account not found

### ISSUE THREAD

**Issue by artBoffin** [ProjectOpenSea/cryptopuff-contracts#1]
When trying to mint, get error:
(node:10604) UnhandledPromiseRejectionWarning: Account not found

I am able to successfully "migrate" the contract onto the rinkeby testnet using the migrate functions:
https://rinkeby.etherscan.io/address/0xea538d569b13aea82cfd04f5cb339f9588869018

However, when I run the "mint" code
https://github.com/ProjectOpenSea/cryptopuff-contracts/blob/master/scripts/mint.js
I get an "Account not found" error at line 36

It appears the hdwallet-provider is the one throwing the error??:
https://github.com/trufflesuite/truffle-hdwallet-provider/blob/def8d45d73c7be77b0b8b3270f5904808d9d2f4d/index.js

When I use the "interact" tab at https://www.withpragma.com/
It successfully mints tokens:
https://rinkeby.etherscan.io/address/0x6b89E8FC4170dF884785faCD29C7700EB3C765b0

**Comment by dfinzer** [comment]
@artBoffin pushed a fix to the repo incorporating your recommendation. Thanks for the help with this!
